version: '3.9'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    env_file:
      - .env
    command: flask run --host=0.0.0.0 --port=5000

  db:
    image: alpine
    container_name: db-container
    volumes:
      - ./database.db:/app/database.db
