name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # Replace with your project's Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit

    # Step 4: Run Bandit security check
    - name: Run Bandit security check
      run: bandit -r .

    # Step 5: Build step (example)
    - name: Build the application
      run: |
        echo "Building application..."
        # Add your build commands here

    # Step 6: Test step (example)
    - name: Run tests
      run: |
        echo "Running tests..."
        # Add your test commands here

    # Step 7: Deploy step (example)
    - name: Deploy to Azure
      run: |
        echo "Deploying application to Azure..."
        # Add your deployment commands here
